### ISSUE TITLE
The "limit" option

### ISSUE THREAD

**Issue by millette** [EmilTholin/image-trace-loader#11]
The readme and example both show a limit option but it's not explained anywhere and doesn't appear in the source either:

https://github.com/EmilTholin/image-trace-loader/search?q=limit&unscoped_q=limit

Should it be removed, or documented?

**Comment by EmilTholin** [comment]
Hi @millette!

Ah, the [`limit` option of the `url-loader` package](https://github.com/webpack-contrib/url-loader#limit) controls at what size breakpoint the `url-loader` won't inline the image as base64 anymore. This option itself is not used in `image-trace-loader`, but the [`skipTraceIfBase64` option](https://github.com/EmilTholin/image-trace-loader#options) is used in conjunction with it.

**Comment by millette** [comment]
Ah, thanks for the clarification. Maybe copying that in the readme would be helpful to others as well.

**Comment by EmilTholin** [comment]
No problem. Yeah, it's mentioned briefly with "It can also be used in conjunction with `url-loader` or `file-loader`", but I will see if I can make that clearer.
