### ISSUE TITLE
[improvement] include demos

### ISSUE THREAD

**Issue by candidodmv** [EmilTholin/image-trace-loader#2]
Maybe will be more productive you show a working sample of your project

**Comment by EmilTholin** [comment]
Thank you for your feedback Vinicius!

What would you like to see? A gif in the readme? A folder with a working webpack example?

![image_trace_loader_example](https://user-images.githubusercontent.com/11573167/31786794-f2bfc7b0-b509-11e7-906f-63fd74ac399c.gif)

**Comment by mehrdaad** [comment]
@EmilTholin hey. thanks for your project. I do think that to get a better clarification of this repo, two things can be done:  

1. Provide a gif (like the mentioned tweet in the README)
2. Create a sample project within the repo so a developer can just clone, ``yarn`` and then see it in action.  

Regards

**Comment by EmilTholin** [comment]
I just [added an example](https://github.com/EmilTholin/image-trace-loader/tree/master/example) to the repository. Thanks again for your feedback!

**Comment by mehrdaad** [comment]
Would be nice to site example in the main README?  
Also providing a gif in the main README :)))
