### ISSUE TITLE
[Request] Include link to my working demo in the README

### ISSUE THREAD

**Issue by itaditya** [EmilTholin/image-trace-loader#3]
Hey Emil, fantastic work with the project. It was so awesome I couldn't wait to make a working example out of it. You can check it out [here](http://trace.surge.sh). 

It would be awesome if you could add it's reference in your README.
Here's the github repo link- https://github.com/itaditya/Trace-Lazy-Load.
This would also close #2

**Comment by EmilTholin** [comment]
Thank you for your nice comment and feedback Aditya!

Your example looks great! I'm planning on adding an `example` folder to the project this weekend. I can link to your repository from there as well.

**Comment by itaditya** [comment]
Awesome :+1:

**Comment by EmilTholin** [comment]
I just [added an example](https://github.com/EmilTholin/image-trace-loader/tree/master/example) to the repository, and the README contains a link to your beautiful example. Thanks again Aditya!

**Comment by itaditya** [comment]
:fireworks: :grinning:
