### ISSUE TITLE
Using CDN Images

### ISSUE THREAD

**Issue by christiannwamba** [EmilTholin/image-trace-loader#4]
Hi,

Wondering if anyone has used this loader with CDN images. My images are on Cloudinary and S3 and I was wondering if there is a use-case with this loader.

Cheers!

**Comment by EmilTholin** [comment]
Hi @christiannwamba!

I think it will be difficult to use this loader if your images are already on a CDN, sadly. However, if you have your images locally, you can use this loader and just set the `publicPath` to your CDN, and upload the images to your CDN in your build step, but that is another use case altogether:

```javascript
// webpack.config.js

module.exports = {
  entry: "./app.js",
  output: {
    filename: "bundle.js",
    publicPath: "https://mycdn.com"
  },
  module: {
    rules: [
      {
        test: /\.(gif|png|jpe?g)$/i,
        use: [
          {
            loader: 'image-trace-loader'
          }
        ]
      }
    ]
  }
}
```
