### ISSUE TITLE
How to do  image dynamic import?

### ISSUE THREAD

**Issue by pogran** [EmilTholin/image-trace-loader#6]
It's my code 

```
const {book} = this.props
const urlImage = `../../../../..${book.image}`
const image = require(urlImage)
```

I can next issue http://prntscr.com/hsknvf  .
   Uncaught Error: Cannot find module "."
    at webpackMissingModule 

How i can to do dynamic import?

**Comment by EmilTholin** [comment]
Hi @pogran! Webpack doesn't work like that, sadly. Your image import has to be static so it can be imported at build time, not at run time.
