### ISSUE TITLE
Safari 11 - Using file URI causes memory leak.

### ISSUE THREAD

**Issue by glemiere** [EmilTholin/image-trace-loader#8]
Hey!

First of all, thank you a lot for this little loader, it's quite useful and well coded, I will probably enjoy making a PR here and there ;)

**Safari 11 leaks a lot while trying to process Base64 string pictures and vectors**. It sucks because if you have a lot of pictures to load (it's kind of the point of lazy loading), then safari gets a serious heart attack loading your web app.

I guess that we could avoid this problem by setting a **new option to serve a file** as well as the Base64 string, **and by adding a constructor to the exported object** who would detect which browser is used if executed on the client (for SSR compatibility) and would change the value of the trace retrieved by the app to a file URL accordingly.

The option would be an array of strings `useFileUrlOn` who could be set, for example, to ['safari', 'ie'] in order to use file URL instead of data URI on Safari and IE8,9,10,11...

Does it sound good ?

**Comment by EmilTholin** [comment]
Hi @glemiere! Thank you for your kind words.

I'm not a big fan of extending the API because of Safari's shortcomings. I would rather fix this in user land instead:

```jsx
import { src, trace } from "./image.jpg";

const isSafari = checkIfSafari();

class Img extends Component {
  state = {
    imageLoaded: false
  };

  setImageLoaded = () => {
    this.setState({ imageLoaded: true });
  };

  render() {
    return (
      <div className="image-wrapper">
        {!isSafari && <img src={this.props.trace} />}
        <img
          src={this.props.src}
          className={`image ${this.state.imageLoaded && `loaded`}`}
          onLoad={this.setImageLoaded}
        />
      </div>
    );
  }
}

ReactDOM.render(
  <Img src={src} trace={trace} />,
  document.getElementById("app")
);
```

**Comment by glemiere** [comment]
Thank you for you answer!

Your example is removing the trace when safari is detected, I'd rather keep it but not as a Base64 string but as a file so it just works without leaking, otherwise it means that this loader can't be used in production with safari at all.

I get it, I hate to alter my designs by writing workarounds to deal with what billions dollar companies don't want to deal with, but we know Apple, this bug might still be there in 2040, as well as our need for clean and cross browser pictures lazy loading.

Would you still consider a fix even if it's different from my first proposal ?

**Comment by EmilTholin** [comment]
I feel like creating a file of the trace would violate the entire purpose of the loader, which is to inline a trace that is available instantly in the browser.

You can fork it and add it to your own version like you said, that would be great.
