### ISSUE TITLE
image trace loader performance?

### ISSUE THREAD

**Issue by jacktang** [EmilTholin/image-trace-loader#9]
Hello,

Thanks for the great project! And we use it in our project, it works fine if images not so much. And in the production env, there are around 10000+ images. We try to build the project using webpack and it throws out `out of memory` error. So did you test the image-trace-loader performance?

Thanks

**Comment by EmilTholin** [comment]
Hi @jacktang! Thank you for your kind words.

I have not done any performance testing with 10 000+ images, sadly. Have you isolated the problem to `image-trace-loader`, and it's just not Webpack that is having trouble with that many modules?

`image-trace-loader` itself does very minimal work per module, and I'm not sure how it could be improved upon.

**Comment by EmilTholin** [comment]
I'm closing this as I see no way of optimizing the loader's performance. It might be worth looking into [giving Webpack more memory](https://github.com/webpack/webpack/issues/1875).

```bash
node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js ...
```
